### PR TITLE
Mostly overview stuff

### PR DESCRIPTION
**Pull request by forevaufo**
- Edited , added functions and added doc string to db_02_function
- Refactored gradebook index to use bootstrap
- Merged student_overview.py into students.py
- Created students/overview
- Removed student_overview folder from view

### CODE REVIEW

**Comment by bpatzke** [comment]
This crashes with a divide-by-zero error when trying to access the following pages:
- Teacher overview for either Bob or Ted
- Class 1 for Bob
- Class 2 for Ted

This might be a data issue, in which case, please have Larry update the data as appropriate.

Either way, This should fail gracefully instead of crashing. For example, we should display the data for the classes that have valid data, and show a warning telling the teacher that errors were encountered while generating the data for the class causing the crash.

**Comment by Larry-Graves** [comment]
I haven't seen this error in a while.  Last I had seen, it was being caused
by some sort of glitch where the gradebook needed to be loaded before the
overview screen.

Not sure what the root cause is, so we might have to just fake it for
tomorrow.

**Comment by forevaufo** [comment]
Byran still awake ?

**Comment by forevaufo** [comment]
Ok i tossed a try statement in there for it to fail gracefully 
image
But something still dont seem right, if the class average is 0% then how does the standard still have value ?
Is this data ? or query ?

**Comment by Larry-Graves** [comment]
it's not data, unless you deleted things

**Comment by forevaufo** [comment]
thats weird..... it worked for class 2 before...

**Comment by forevaufo** [comment]
Ok, problem found and fixed, new pull request is up. Sorry for creating more work for you Bryan.
It was the greater and smaller sign in one of the query for the average function, those little things are so confusing sometimes.

**Pull request closed without merging**
