### PR TITLE
updated unit test example

### PR DESCRIPTION
**Pull request by forevaufo**
non-working example
just updating to whatever i have so far

### CODE REVIEW

**Comment by bpatzke** [comment]
Please fix the issue I sent you and resubmit the pull request.

**Comment by forevaufo** [comment]
what did you sent me ? i dont see it anywhere

**Comment by bpatzke** [comment]
I think it shows up as a pull request on your repository.

**Comment by forevaufo** [comment]
Sorry about that, i fixed it

**Pull request closed without merging**
