### PR TITLE
updates and additions

### PR DESCRIPTION
**Pull request by Joseph-Richard**
- deleted code problem in student.py
- added create methods for students.py and grades.py
- added student_grade table in student.py

### CODE REVIEW

**Comment by Larry-Graves** [comment]
what did you change in the import files and testing database?

**Comment by Joseph-Richard** [comment]
Nothing. I dont know why its saying i touched them. All i want to do is add
my changes that I made in the files i was assigned. this is my third
commit, yet i keep running into issues. im about to delete it all and set
it all up again.

**Comment by Larry-Graves** [comment]
are you committing everything? It should only show what you manually add
top commit.

**Comment by Joseph-Richard** [comment]
I'm only committing what i made changes to.

**Pull request closed without merging**
