### PR TITLE
unit testing stuff

### PR DESCRIPTION
**Pull request by forevaufo**
unit testing stuff

### CODE REVIEW

**Comment by bpatzke** [comment]
Allan,

Please fix the indentation on the ``GradeBookController.py``. It should be 4 spaces.

Thanks,

Bryan

**Comment by forevaufo** [comment]
should be fixed

**Comment by bpatzke** [comment]
My mistake. The file `tests/controllers/GradeBookController.py` has tabs instead of spaces on lines 7 through 14. Please convert them to spaces.

**Comment by bpatzke** [comment]
This will be addressed in a future pull request.

**Pull request closed without merging**
