### PR TITLE
Created "create" for grade controller

### PR DESCRIPTION
**Pull request by forevaufo**
Created "create" for grade controller
Edited student index/filter

### CODE REVIEW

**Comment by bpatzke** [comment]
Allan,

Instead of taking you to the home page, the create page should route you back to where you came from using ``request.env.http_referer`` when it can't process the request.

Also, you can use ``response.flash`` to display a message telling the user what happened.

This page has information about both:
http://www.web2py.com/books/default/chapter/29/04/the-core

**Comment by forevaufo** [comment]
Bryan, request.env.http_referer does not want to work, request.env.http_referer always return "None".

Any tips ?

**Comment by bpatzke** [comment]
You need to be directed to the page via a link. If you just type in the URL, there is no referrer.

If there is no referrer, you should default to redirecting to the main page.

**Comment by forevaufo** [comment]
Awesome, fixed it. Thanks Bryan

**Pull request merged**
