### PR TITLE
Fix issue #87

### PR DESCRIPTION
**Pull request by bpatzke**
Fix issue #87 - student assignments query returning too many results.

### CODE REVIEW

**Comment by Larry-Graves** [comment]
Out of curiosity, what was wrong?  Our Overview screen is doing something
similar, and I'm guessing the genesis is the same.

**Comment by bpatzke** [comment]
I forgot to add a clause to restrict the assignments to those for the associated class.

**Comment by Larry-Graves** [comment]
I'm willing to bet using your new function will solve our issue in the
Overview screen.  I'll have Allan test it out.

**Comment by bpatzke** [comment]
It probably won't - at least not completely. The main part of the fix is the change in the student assignments query.

**Pull request merged**
